# Generated by Django 3.2.10 on 2022-02-01 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('smartcleancityapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bin',
            fields=[
                ('bid', models.AutoField(primary_key=True, serialize=False)),
                ('alat', models.FloatField()),
                ('along', models.FloatField()),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('did', models.CharField(blank=True, default='', max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('photo', models.FileField(upload_to='images/')),
                ('clat', models.FloatField()),
                ('clong', models.FloatField()),
                ('status', models.CharField(default='not assigned', max_length=20)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='user',
        ),
    ]
